apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: grafana
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: grafana-service
    weight: 100
  ports:
    targetPort: 3000
  wildcardPolicy: None