apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
  source:
    repoURL: https://github.com/ludydoo/acscs-observability
    targetRevision: HEAD
    path: grafana-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators