apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-monitoring
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ludydoo/acscs-observability
    targetRevision: HEAD
    path: openshift-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-monitoring