apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: central-rules
spec:
  groups:
    - name: rhacs-central
      rules:
        - alert: TestAlert
          expr: verb:apiserver_request_duration_seconds_bucket:rate1m > 0
          labels:
            severity: critical
          annotations:
            summary: "Central container `{{ $labels.pod }}/{{ $labels.container }}` database connection in namespace `{{ $labels.namespace }}` is down or is in a bad shape."
            description: "Central container `{{ $labels.pod }}/{{ $labels.container }}` database connection in namespace `{{ $labels.namespace }}` has been down or is in a bad shape for at least 10 minutes."
            sop_url: "https://gitlab.cee.redhat.com/stackrox/acs-managed-service-runbooks/blob/master/sops/dp-010-rhacs-instance-db-unavailable.md"
