apiVersion: v1
kind: Service
metadata:
  name: custom-prometheus
  namespace: openshift-user-workload-monitoring
spec:
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: user-workload
  type: ClusterIP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: prometheus-custom-route
  namespace: openshift-user-workload-monitoring
spec:
  to:
    kind: Service
    name: custom-prometheus
    weight: 100
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None